README.md
This just adds the URL to the blog entry at https://blog.docker.com/2015/11/docker-toolbox-compose/
=> Update README.md with reference to the Blog

LICENSE, MAINTAINERS
cc @aanand @fermayo @maximeheckel
=> Add LICENSE and MAINTAINERS

dockercloud.yml, result-app/docker-compose.test.yml, result-app/tests/Dockerfile, result-app/tests/render.js, result-app/tests/tests.sh
=> Docker Cloud stack file and CI tests

result-app/server.js, result-app/views/app.js, result-app/views/index.html, result-app/views/stylesheets/style.css
@aanand - good to put this in here?
=> Various pieces of vote refactoring

README.md
=> Replace Java with .NET

worker/Dockerfile
Changing base image to Microsoft's release version
=> Updating Worker Dockerfile

worker/Dockerfile
Reverts docker/example-voting-app#36
=> Revert "Updating Worker Dockerfile"

docker-compose-simple.yml, docker-compose.yml
moved docker-compose.yml to docker-compose-simple.yml and restored older version of docker-compose.yml with networks and volumes
=> Adding additional compose file

MAINTAINERS
/cc @aanand @manomarks
Signed-off-by: Ben Firshman <ben@firshman.co.uk>
=> Add Mano as a maintainer

result/views/index.html, result/views/stylesheets/style.css
Labels changes according to the options i.e. Java and .Net 
Thank you.
Signed-off by,
mohan08p
Mohan Pawar
=> Labels changes according to options

result/views/index.html, result/views/stylesheets/style.css
Reverts docker/example-voting-app#45
This is inconsisent – the voting app is cats vs. dogs. If we want to change the options, we should have a setting for it.
=> Revert "Labels changes according to options"

result/package.json, result/server.js
fix to handle postgres timeouts:  https://github.com/docker/example-voting-app/issues/41
=> added connection pooling to postgres to prevent client timeouts

result/package.json, result/server.js
Reverts docker/example-voting-app#54
This was causing #55
=> Revert "added connection pooling to postgres to prevent client timeouts"

docker-stack.yml
Adding in docker-stack.yml with the new V3 compose syntax.
=> Adding in docker-stack.yml

worker/src/Worker/Program.cs
While testing this example app in my company, I have noticed that redis connection is lost after a few minutes of application inactivity. 
This is a common redis bug, so I found the recommended solution and implement it into this example app. 
I have tested it a few times - the app wasn't active for 24h and still worked fine.
Please can you review the code, maybe it will help someone :)
Thank you.
Manuel Belsak
=> Establishe redis connection after its lost after a few minutes

docker-compose-k8s.yml
replicas cant be 2 because of port allocation
=> Version Was invalid, Fix to Version3 docker-compose

k8s-specifications/vote-namespace.yml
=> Add missing vote namespace

worker/src/Worker/Program.cs
Fix the case of losing a vote when actual vote found in Redis and db connection was closed
=> Fix a case of lost vote.

.github/workflows/call-docker-build-result.yaml, .github/workflows/call-docker-build-vote.yaml
Many demos include a before and after tag on vote and result apps. This adds those to autobuilds.
=> add before and after tags for demos

docker-compose.images.yml, docker-compose.yml, result/docker-compose.test.yml
=> remove redis port from compose files

.vscode/launch.json, README.md, docker-compose.images.yml, docker-compose.yml, docker-stack.yml, k8s-specifications/result-service.yaml, k8s-specifications/vote-service.yaml
This PR is changing the published ports from 5000/5001 to 8080/8081 to avoid a conflict on Mac machines (where an AirPlay receiver is running by default).
=> Change ports
