dockersamples/example-voting-app

docker-compose-javaworker.yml

With docker-compose 1.10-rc1 build from this file was failing. Fix this by using the new build syntax with explicit `context` & `dockerfile`.

Fix docker-compose-javawork.yml

---

docker-stack.yml

Visualizer needs to run on a manager node

adding a placement constraint on visualizer

---

docker-stack.yml

If a loadbalancer is used for this service, then socket.io will fail as the session will be created only in one container.

Update replicas to 1 in result service

---

result/Dockerfile
result/tests/Dockerfile

**Problem**: `result` Image won't build on Docker Hub due to failed tests using `result/docker-compose.test.yml` which uses `result/tests/Dockerfile`. That Dockerfile fails building due to outdated phantomjs install method.
**Fix**: Update test Dockerfile to use yarn for installing phantomjs.
Also: Updating result app to latest stable node.js

updating result app node version and fixing tests

---

result/Dockerfile
result/tests/Dockerfile
worker/src/Worker/Program.cs

*Problem:* The dotnet worker, by default, will consume a full CPU by querying redis as fast as it can, you can use `redis-cli monitor` to see dozens of LPOP's a second. This isn't great for local demos, especially when on battery.
*Solution:* add a `Thread.Sleep(100);` so it queries every 100ms max. I tested up to 500ms without any perceived delay on localhost, but 100ms still kept CPU usage quite low so I felt this was a good compromise.
This doesn't seem to be an issue with Java version, as it uses `BLPOP` to block rather than the rapid queries approach used by dotnets LPOP, which [seems to be a limitation of the chosen redis package](https://stackexchange.github.io/StackExchange.Redis/PipelinesMultiplexers) for dotnet.

prevent dotnet worker from consuming all cpu

---

docker-compose.yml

Added "depends_on" for the worker to ensure startup after redis to fix occasional start-up order barfing. Sometimes worker started too early before redis and barfed with:
```
worker_1  |    at System.Net.Dns.<>c.<GetHostEntryAsync>b__16_1(IAsyncResult asyncResult)
worker_1  |    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
worker_1  |    --- End of inner exception stack trace ---
worker_1  |    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
worker_1  |    at Worker.Program.GetIp(String hostname) in /code/src/Worker/Program.cs:line 123
worker_1  |    at Worker.Program.OpenRedisConnection(String hostname) in …
```

fix start-up order, depend worker on redis in docker-compose.yml

---

worker/src/Worker/Program.cs

Keep Redis connection stored so that it's not lost and we avoid reconnecting all the time.

Don't lose Redis connection on reconnect

---

result/tests/tests.sh

Hi!
This example is run in the test suite of Docker for Mac.  We also run spellcheck on our tree.  Shellcheck now complains about misleading \-escapes in double quotes, and suggest doubling them.
While at it, I have rewritten some control flow into a more conventional layout.
Cheers!

tests: please shellcheck

---

worker/Dockerfile.j

This patch optimizes the java-worker image;
- Use multi-stage build to separate the build-stage from the "deploy" stage
- Switch to the official Maven image, instead of manual installation of Maven.
The official Maven image is also based on the `openjdk` repository on Docker
Hub, which replaces the (now deprecated) `java` repository.
- Use `COPY` instead of `ADD` to follow best-practice
- Add `-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap` arguments
so that JAVA will take memory-limits into account
- Use a JRE base image for the final build-stage
This change brings the size of the final image down from 184MB to 87MB
ping @ManoMarks PTAL

Optimize java-worker image

---

result/Dockerfile

This patch makes some optimizations in the result service's image;
- switch to `node:8.9-alpine`, which a smaller base image
- use `https://` for the registry
- use `COPY` instead of `ADD`, following best pracice
- cleanup npm cache, and combine steps to reduce image size
These changes bring down the image size from 248MB to 81.2MB
ping @ManoMarks @BretFisher PTAL

Optimize result image

---

docker-compose-javaworker.yml

The `--debug` option is deprecated and caused the result
service to not start:
result_1  | [nodemon] 1.14.7
result_1  | [nodemon] to restart at any time, enter `rs`
result_1  | [nodemon] watching: *.*
result_1  | [nodemon] starting `node --debug server.js`
result_1  | (node:20) [DEP0062] DeprecationWarning: `node --debug` and `node --debug-brk` are invalid. Please use `node --inspect` or `node --inspect-brk` instead.
result_1  | [nodemon] app crashed - waiting for file changes before starting...
This patch removes the `--debug` option, as it's not needed,
and no longer present in the other example stacks.
Same fix as https://github.com/dockersamples/example-voting-app/pull/95, but for the javaworker example
ping @ManoMarks

Fix javaworker result service not starting

---

docker-compose-windows-1809.yml
docker-stack-windows-1809.yml
result/dotnet/Dockerfile.1809
vote/dotnet/Dockerfile.1809
worker/dotnet/Dockerfile.1809

Added Dockerfiles, compose and stack files for building and running on Windows Server 2019.

Add Windows 1809 support

---

docker-stack.yml

Fixes #108
In docker-compose.yml and other "designed for development" yaml files, It's typical to publish database and key/value ports for localhost access. However, it's not necessary to publish the redis port in swarm server-based solutions.

Remove published swarm stack redis port

---

k8s-specifications/worker-deployment.yaml

This prevent the creation of the worker's Deployment.

Incorrect label for worker Deployment in .spec.selector.matchLabels

---

docker-compose-javaworker.yml
docker-compose-k8s.yml
docker-compose-simple.yml
docker-compose.yml
docker-stack-simple.yml
docker-stack.yml
k8s-specifications/db-deployment.yaml
kube-deployment.yml
result/docker-compose.test.yml
result/server.js
worker/src/Worker/Program.cs
worker/src/main/java/worker/Worker.java

The official Postgres image pushed a change that will prevent a fresh database from initializing without a password.
Trying to start with an empty db volume results in this error from the `db` container:
```
db        | Error: Database is uninitialized and superuser password is not specified.
db        |        You must specify POSTGRES_PASSWORD for the superuser. Use
db        |        "-e POSTGRES_PASSWORD=password" to set it in "docker run".
db        |
db        |        You may also use POSTGRES_HOST_AUTH_METHOD=trust to allow all connections
db        |        without a password. This is *not* recommended. See PostgreSQL
db        |        documentation about "trust":
db        |        https://www.postgresql.org/docs/current/auth-trust.html
```
- Explicitly set the default Postgres …

Set an explicit username and password for the db service

---

docker-compose-windows-1809.yml
docker-compose.yml
result/dotnet/Dockerfile.1809
vote/dotnet/Dockerfile.1809
worker/Dockerfile
worker/dotnet/Dockerfile.1809
worker/src/Worker/Worker.csproj

Updates all the .NET Core components to 2.1 and uses the SDK and runtime images from MCR.

Fix .NET Core images

---

result/dotnet/Dockerfile.1809
result/dotnet/Result/Result.csproj
vote/dotnet/Dockerfile.1809
vote/dotnet/Vote/Vote.csproj
worker/Dockerfile
worker/dotnet/Dockerfile.1809
worker/dotnet/Worker/Worker.csproj
worker/src/Worker/Worker.csproj

This PR updates dotnet from 2.1 to 3.1 to fix an issue that was raised on **Apple M1** mentioned in Docker Community Slack:
> Hi, I was trying to run this docker sample on my Macbook Air M1 but I get the following errors. Any thoughts on how I could fix this?
Sample - https://github.com/dockersamples/example-voting-app
It turns out that the dotnet 2.1 multi-arch image only supports linux/amd64 and linux/arm/v7, the newer dotnet 3.1 also has linux/arm64 in the manifest list.
I hope that doesn't break anything in the sample app. I could build and run it with a simple `docker-compose up`.

Update dotnet 3.1 (needed to support Apple Silicon M1)

---

docker-compose.yml
result/Dockerfile
result/package-lock.json
result/package.json

The current `node:10-slim` for the result app won't build/run for various reasons, so here's some updates:
- Updated Dockerfile to `node:18-slim`
- Moved `tini` install to a multi-arch compatable method (apt)
- Changed `tini` execution to the recommened ENTRYPOINT approach
- Updated all npm dependencies to latest, execpt socket.io which requires code migration
- Fixed broken db connection caused by node > v12 by upgrading the pg node module to latest
I've tested this locally and everything works. I can submit a vote, see it processed by worker, and now correctly displayed in result app.

update result node.js deps for multi-arch

---

.github/dependabot.yml
.github/workflows/call-docker-build-result.yaml
.github/workflows/call-docker-build-vote.yaml
.github/workflows/call-docker-build-worker.yaml

This PR creates a docker build-and-push workflow for the three apps in this repo.
It uses a reusable workflow that's in the `dockersample/.github` repo.
It also adds a monthly dependabot scan for any GHA step updates.
Note that arm/v7 builds of worker (.net core 3.1) don't work with QEMU-emulated builds, so I've added a task to the [project backlog](https://github.com/orgs/dockersamples/projects/1/views/1) to redeisgn that build.

adding GHA for docker builds and dependabot config for GHA

---

worker/Dockerfile

Various platforms report different TARGETPLATFORM to Docker. Previously, builds might fail on an arm64 machine if it reported `linux/arm64/v8` to BuildKit. This fixes that.

Fix dotnet build

---

README.md
k8s-specifications/db-deployment.yaml
k8s-specifications/db-service.yaml
k8s-specifications/redis-deployment.yaml
k8s-specifications/redis-service.yaml
k8s-specifications/result-deployment.yaml
k8s-specifications/result-service.yaml
k8s-specifications/vote-deployment.yaml
k8s-specifications/vote-namespace.yml
k8s-specifications/vote-service.yaml
k8s-specifications/worker-deployment.yaml

This is debatable, but I find it easier to avoid mandating or creating namespaces in simple K8s examples. We can't assume they know namespace basics, how to switch namespaces etc.  Local dev setups like Docker Desktop are fine with demos going in `default`.
This PR is to remove all references to the vote namespace in manifests, and it'll just create the resources in your current namespace.
I've also updated the docs to reflect that, which I think will work better for people using this repo to get started with Docker and K8s.

Remove namespace from k8s example

---

worker/Dockerfile

Since .NET 7.0.300, the new `-a/--arch` argument is supported that accepts the same formatting as Docker's $TARGETARCH. This greatly simplifies the restore and build commands in this sample.
See @richlander's [blog post](https://devblogs.microsoft.com/dotnet/improving-multiplatform-container-support/) and https://github.com/dotnet/sdk/issues/30369 for more context.

Simplify .NET multi-platform Dockerfile

---

.vscode/launch.json
docker-compose.yml

Simply adds debug support for the results service, making it possible to set breakpoints and debug the node app

Add debug port support for the results (node) app

---

docker-compose.yml

Couple of small fixes/adjustments to 1) better secure the debug port and 2) don't break at the start

Don't break on user script at start and bind debug only locally

---

docker-compose.yml
vote/Dockerfile

Recent versions of Flask don't do the automatic restart even with debug turned on and require watchdog to be installed. I ended up creating another stage that does this and updated the Compose file to use that stage as the target.
Also fixed file mount changes, due to the recent working directory changes (oops!)

Fix file mounts (work dir change) and python reloading

---

.gitattributes

CRLF in .sh healthcheck scripts seems to causes failures.
git clone with default parameters on Windows would change all line endings to CRLF.
The .gitattributes file makes sure the LF line endings are preserved for .sh files.

Adding a git attributes file to avoid EOL issues

---

result/Dockerfile
seed-data/Dockerfile
vote/Dockerfile
worker/Dockerfile

- **lint: fix LegacyKeyValueFormat**
- **lint: fix FromAsCasing**
- **lint: fix JSONArgsRecommended**
- **lint: fix InvalidDefinitionDescription**

lint: fix Dockerfile build check warnings
